version: "3.7"

services:
  app:
    build:
      context: .
      target: development
    ports:
      - 3000:3000
    volumes:
      - ./:/home/node/app
      - node-cache:/home/node/app/node_modules
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    restart: always
    env_file:
      - .db.env
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  node-cache: {}
  db-data: {}
